#!/bin/sh

. /etc/rc.subr

name="adguardhome"
rcvar="adguardhome_enable"
adguardhome_user="adguard"
adguardhome_command="/home/adguard/.config/AdGuardHome/AdGuardHome"
pidfile="/var/run/${name}/pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${adguardhome_command}"

load_rc_config $name
: ${adguardhome_enable:=no}

run_rc_command "$1"
